// Global type augmentation for window.ENV_CONFIG
// Loaded at runtime via env-config.js generated by docker-entrypoint.sh

declare global {
  interface Window {
    ENV_CONFIG?: {
      TOY_SERVICE_URL?: string;
      TRIP_SERVICE_URL?: string;
      DEMO_DATA_API_URL?: string;
      MSAL_REDIRECT_URI?: string;
      OTEL_COLLECTOR_URL?: string;
      ENVIRONMENT?: string;
      SERVICE_VERSION?: string;
    };
  }
}

export {};
