apiVersion: v1
data:
  config.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        send_batch_size: 1024
        timeout: 10s
      memory_limiter:
        check_interval: 1s
        limit_mib: 400

    exporters:
      azuremonitor:
        connection_string: ${env:APPLICATIONINSIGHTS_CONNECTION_STRING}
      debug:
        verbosity: basic
      otlp:
        endpoint: aspire-dashboard:18889
        tls:
          insecure: true

    service:
      extensions:
      - health_check
      pipelines:
        logs:
          exporters:
          - otlp
          - debug
          - azuremonitor
          processors:
          - memory_limiter
          - batch
          receivers:
          - otlp
        metrics:
          exporters:
          - otlp
          - debug
          - azuremonitor
          processors:
          - memory_limiter
          - batch
          receivers:
          - otlp
        traces:
          exporters:
          - otlp
          - debug
          - azuremonitor
          processors:
          - memory_limiter
          - batch
          receivers:
          - otlp
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: platform-observability:/ConfigMap:toytrip-staging/otel-collector-config
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"extensions:\n  health_check:\n    endpoint: 0.0.0.0:13133\n\nreceivers:\n  otlp:\n    protocols:\n      grpc:\n        endpoint: 0.0.0.0:4317\n      http:\n        endpoint: 0.0.0.0:4318\n\nprocessors:\n  batch:\n    send_batch_size: 1024\n    timeout: 10s\n  memory_limiter:\n    check_interval: 1s\n    limit_mib: 400\n\nexporters:\n  azuremonitor:\n    connection_string: ${env:APPLICATIONINSIGHTS_CONNECTION_STRING}\n    endpoint: https://dc.services.visualstudio.com/v2/track\n  debug:\n    verbosity: basic\n  otlp:\n    endpoint: aspire-dashboard:18889\n    tls:\n      insecure: true\n\nservice:\n  extensions:\n  - health_check\n  pipelines:\n    logs:\n      exporters:\n      - otlp\n      - debug\n      - azuremonitor\n      processors:\n      - memory_limiter\n      - batch\n      receivers:\n      - otlp\n    metrics:\n      exporters:\n      - otlp\n      - debug\n      - azuremonitor\n      processors:\n      - memory_limiter\n      - batch\n      receivers:\n      - otlp\n    traces:\n      exporters:\n      - otlp\n      - debug\n      - azuremonitor\n      processors:\n      - memory_limiter\n      - batch\n      receivers:\n      - otlp\n"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"platform-observability:/ConfigMap:toytrip-staging/otel-collector-config"},"labels":{"app.kubernetes.io/component":"collector","app.kubernetes.io/name":"otel-collector","app.kubernetes.io/part-of":"platform-observability"},"name":"otel-collector-config","namespace":"toytrip-staging"}}
  creationTimestamp: "2025-11-25T09:51:42Z"
  labels:
    app.kubernetes.io/component: collector
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: platform-observability
  name: otel-collector-config
  namespace: toytrip-staging
  resourceVersion: "64640"
  uid: cf755a1d-2ddc-4d48-819c-02f964198b81
