apiVersion: approuting.kubernetes.azure.com/v1alpha1
kind: NginxIngressController
metadata:
  name: nginx
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  controllerNamePrefix: nginx
  loadBalancerAnnotations: 
    service.beta.kubernetes.io/azure-pip-name: "{{ .Values.ingress.publicIpName }}"
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "{{ .Values.ingress.resourceGroup }}"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
  {{- if .Values.ingress.forceSSLRedirect }}
  defaultSSLCertificate:
    forceSSLRedirect: true
  {{- end }}
