{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "toy.serviceAccountName" . }}
  labels:
    {{- include "toy.labels" . | nindent 4 }}
  {{- $wiEnabled := and .Values.workloadIdentity.enabled (ne (default "" .Values.workloadIdentity.clientId) "") }}
  {{- if or $wiEnabled .Values.serviceAccount.annotations }}
  annotations:
    {{- if $wiEnabled }}
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.auth.tenantId | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
