{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: collector
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.otelCollector.service.type }}
  selector:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: collector
  ports:
  - name: grpc-otlp
    port: {{ .Values.otelCollector.service.grpcPort }}
    targetPort: otlp-grpc
    protocol: TCP
    appProtocol: grpc
  - name: otlp-http
    port: {{ .Values.otelCollector.service.httpPort }}
    targetPort: otlp-http
    protocol: TCP
{{- end }}
