gateway:
  enabled: true
  name: toytrip-gateway
  annotations: {}
  infrastructure:
    annotations: {}
  listeners:
    - name: http
      hostname: "{{ .Values.ingress.publicIpFqdn }}"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      hostname: "{{ .Values.ingress.publicIpFqdn }}"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        secretName: toytrip-tls
      allowedRoutes:
        namespaces:
          from: Same
certificate:
  enabled: true
  clusterIssuer: letsencrypt
  secretName: toytrip-tls
  dnsNames:
    - "{{ .Values.ingress.publicIpFqdn }}"
