apiVersion: v1
kind: Service
metadata:
  name: {{ include "addon.api.fullname" . }}
  labels:
    {{- include "addon.labels" . | nindent 4 }}
    {{- include "addon.api.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "addon.api.selectorLabels" . | nindent 4 }}
