apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "addon.worker.fullname" . }}
  labels:
    {{- include "addon.labels" . | nindent 4 }}
    {{- include "addon.worker.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "addon.worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "addon.worker.selectorLabels" . | nindent 8 }}
        {{- if .Values.workloadIdentity.enabled }}
        azure.workload.identity/use: "true"
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "addon.serviceAccountName" . }}
      containers:
      - name: addon-worker
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        command:
          {{- toYaml .Values.worker.command | nindent 10 }}
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ tpl ($value | toString) $ | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.worker.resources | nindent 10 }}
      {{- if gt (int .Values.worker.replicaCount) 1 }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            {{- include "addon.worker.selectorLabels" . | nindent 12 }}
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            {{- include "addon.worker.selectorLabels" . | nindent 12 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
